from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ActionableInputs:
    ai_urgency: str | None  # Low/Med/High
    resolution_days: int | None
    rating: float | None  # 1..5
    forward_count: int | None
    ai_reopen_risk: str | None  # High/Medium/Low/Unknown
    ai_confidence: str | None  # High/Medium/Low


def _norm(s: str | None) -> str:
    return (s or "").strip().lower()


def compute_actionable_score(x: ActionableInputs) -> int:
    """
    Deterministic 1..100 score (NOT generated by Gemini).

    Intuition:
    - Urgency and reopen risk drive action.
    - Long resolution tail increases actionability.
    - Low citizen rating increases actionability.
    - Multiple forwarding events add operational friction.
    - Low AI confidence slightly penalizes the score.
    """
    score = 10

    urg = _norm(x.ai_urgency)
    if urg in ("high",):
        score += 35
    elif urg in ("med", "medium"):
        score += 20
    elif urg in ("low",):
        score += 10

    # SLA tail: emphasize long closures
    rd = x.resolution_days
    if rd is not None:
        if rd >= 60:
            score += 30
        elif rd >= 30:
            score += 22
        elif rd >= 14:
            score += 12
        elif rd >= 7:
            score += 6

    # Citizen feedback (missing allowed)
    r = x.rating
    if r is not None:
        if r <= 1.5:
            score += 18
        elif r <= 2.5:
            score += 12
        elif r <= 3.5:
            score += 6

    # Forwarding signals
    fc = int(x.forward_count or 0)
    if fc >= 3:
        score += 12
    elif fc == 2:
        score += 8
    elif fc == 1:
        score += 4

    rr = _norm(x.ai_reopen_risk)
    if rr in ("high",):
        score += 18
    elif rr in ("medium", "med"):
        score += 10
    elif rr in ("low",):
        score += 4

    conf = _norm(x.ai_confidence)
    if conf in ("low",):
        score -= 12
    elif conf in ("medium", "med"):
        score -= 6

    if score < 1:
        score = 1
    if score > 100:
        score = 100
    return int(score)


